### PR TITLE
Update the dependencies for Jupyter

### PR DESCRIPTION
**Pull request by ValentinMouret**

### CODE REVIEW

**Comment by mpasa** [comment]
Or maybe we can force the minor version on `requirements.in`, not sure.

**Comment by ValentinMouret** [comment]
I’ll try with bumping to 0.16.0. It’s currently the [latest version][https://pypi.org/project/Werkzeug/]

**Comment by ValentinMouret** [comment]
The image is pushed, you should see if we still have the dependency somewhere.

**Comment by mpasa** [comment]
What do you mean? I see no changes for it in `requirements.txt`

```
werkzeug==0.15.2 \
    --hash=sha256:0a73e8bb2ff2feecfc5d56e6f458f5b99290ef34f565ffb2665801ff7de6af7a \
    --hash=sha256:7fad9770a8778f9576693f0cc29c7dcc36964df916b83734f4431c0e612a7fbc \
    # via tensorboard
```

**Comment by ValentinMouret** [comment]
> What do you mean? I see no changes for it in `requirements.txt`
> 
> ```
> werkzeug==0.15.2 \
>     --hash=sha256:0a73e8bb2ff2feecfc5d56e6f458f5b99290ef34f565ffb2665801ff7de6af7a \
>     --hash=sha256:7fad9770a8778f9576693f0cc29c7dcc36964df916b83734f4431c0e612a7fbc \
>     # via tensorboard
> ```

Woopsy, I did not push my commit. Here it is

**Pull request merged**
